### ISSUE TITLE
Not running at night

### ISSUE THREAD

**Issue by datapharmer** [dthowell/DeclarativeScheduler#1]
I'm not sure if this is a bug in salesforce or somewhere else, but if I schedule a report to trigger declarative scheduler at 2 or 3am it never executes. If I run it manually it works and if I run it 10am it works. Any ideas???

**Comment by dthowell** [comment]
Hi, I'm glad the tool is (mostly) working for you. I do not see any reason why the code wouldn't run at certain times of the day.

- Check that after scheduling the report it shows in the "Scheduled Jobs" in the setup menu 
![image](https://user-images.githubusercontent.com/21028276/27308064-e65f75f6-55a0-11e7-85d3-39b04c8dbe61.png)
- Check nothing else is running at that time. 
- Try it at 3am or 4am to just check
- If not there maybe something in the error logs (I think if it captures an error it could email you a link to the report with the error and ask you to reschedule it)

**Comment by danhowellnz** [comment]
Hi datapharmer, 

I know it's been a long time, I have updated the class to add in email notifications on any errors it has while trying to run. It will email the last person who modified the report. 

good luck
Daniel
